package CenterServerApp;


/**
* CenterServerApp/CenterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Tuesday, 19 June, 2018 9:23:30 PM EDT
*/

public interface CenterOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
  String createSRecord (String firstName, String lastName, String courseRegistered, String status, String statusDate, String managerId);
  String getRecordCounts (String managerId);
  String editRecord (String recordId, String fieldName, String newValue, String managerId);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  void shutdown ();
} // interface CenterOperations
