package CenterServerApp;


/**
* CenterServerApp/Center.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Tuesday, 19 June, 2018 9:23:30 PM EDT
*/

public interface Center extends CenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Center
