package CenterServerApp;


/**
* CenterServerApp/Center.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Saturday, 28 July, 2018 10:44:25 AM EDT
*/

public interface Center extends CenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Center
