package CenterServerApp;


/**
* CenterServerApp/CenterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Saturday, 28 July, 2018 10:44:25 AM EDT
*/

public interface CenterOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
  String createSRecord (String firstName, String lastName, String courseRegistered, String status, String statusDate, String managerId);
  String getRecordCounts (String managerId);
  String editRecord (String recordId, String fieldName, String newValue, String managerId);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String crashProcess (String port, String location);
  void shutdown ();
} // interface CenterOperations
